services:
  eureka:
    build:
      context: ../eureka-server
    image: vslab/eureka_server
    ports: 
      - "8761:8761"
    networks:
      - application

  product:
    build:
      context: ../products
    image: vslab/products
    ports:
      - "8085:8085"
    networks:
      - application
    links:
      - eureka
    depends_on:
      - eureka

  category:
    build:
      context: ../categories
    image: vslab/categories
    ports:
      - "8086:8086"
    networks:
      - application
    depends_on:
      - eureka 
      
  users:
    build:
      context: ../users
    image: vslab/users
    ports:
      - "8088:8088"
    networks:
      - application
    depends_on:
      - eureka 

  roles:
    build:
      context: ../roles
    image: vslab/roles
    ports:
      - "8089:8089"
    networks:
      - application
    depends_on:
      - eureka

  catalogue:
    build:
      context: ../catalogue
    image: vslab/catalogue
    depends_on:
      - eureka
    ports:
      - "8087:8087"
    networks:
      - application
      
  account:
    build:
      context: ../account
    image: vslab/account
    depends_on:
      - eureka
    ports:
      - "8090:8090"
    networks:
      - application
    
  zuul:
    build: 
      context: ../edge_server
    image: vslab/zuul
    depends_on:
      - eureka
    ports: 
      - "8091:8091"
    networks:
      - application
   
  auth-server:
    build:
      context: ../auth-server
    image: vslab/auth-server
    depends_on:
      - eureka
    ports:
      - "8092:8092"
    networks:
      - application

####inlcude legacy webshop

  legacywebshop:
    build:
      context: ../webshop-application
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8080"
    networks:
      - application
    volumes:
      - ./debug:/logs

  web-shop-db-image:
    build:
      context: ../webshop-application
      dockerfile: ./docker/DockerfileMySQL
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: c8de110f37300a53a971749
      MYSQL_DATABASE: webshop
      MYSQL_USER: webshopuser
      MYSQL_PASSWORD: 240b2c6d58ff2ce2f508b49f
    ports:
      - "3306:3306"
    networks:
      - application

networks:
  application:
    driver: bridge
