spring:
  application:
    name: authorization-server
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
server:
  port: 8092
eureka:
  client:


    serviceUrl:
      #ohne docker
      #      defaultZone: http://localhost:8761/eureka/
      #docker
      defaultZone: http://eureka:8761/eureka/

  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

    #docker config
    hostname : eureka
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'

webshop-oauth:
  clientId: webshop-client
  secret: webshop-secret
  jwt-signing-key: not-so-secret-key
