server:
  port: 8085
spring:
  application:
    name: product-service
eureka:
  client:
    serviceUrl:
      #ohne docker
      #      defaultZone: http://localhost:8761/eureka/
      #docker
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
      #docker config
      hostname: eureka