spring:
  application:
    name: authorization-service
security:
  oauth2:
    resource:
      filter-order: 3
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 8092
eureka:
  client:


    serviceUrl:
      #ohne docker
      #      defaultZone: http://localhost:8761/eureka/
      #docker
      defaultZone: http://eureka:8761/eureka/

  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"

    #docker config
    hostname : eureka
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'
