server:
  port: 8090
spring:
  application:
    name: account-proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
      hostname : eureka
hystrix:
  dashboard:
    proxy-stream-allow-list: '*'

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth2:
    client:
      clientId: webshop-client
      clientSecret: webshop-secret
      accessTokenUri: http://auth-server:8092/oauth/token
      userAuthorizationUri: http://auth-server:8092/oauth/authorize
    resource:
      token-info-uri: http://auth-server:8092/oauth/check_token
