server:
  port: 8089
spring:
  application:
    name: role-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
      instanceId: "${spring.application.name}:${random.value}"
      hostname: eureka

security:
  oauth2:
    client:
      clientId: role-service-client
      clientSecret: role-service-secret
      accessTokenUri: http://auth-server:8092/oauth/token
      userAuthorizationUri: http://auth-server:8092/oauth/authorize
    resource:
      token-info-uri: http://auth-server:8092/oauth/check_token